language: java

jdk:
  - oraclejdk9

script:
  ./gradlew assemble --stacktrace && ./gradlew check --stacktrace

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
